export type DeviceIdentityErrorCode =
  | "CERTIFICATE_AUTHORITY_CONFLICT"
  | "CERTIFICATE_AUTHORITY_KEY_UNAVAILABLE"
  | "CERTIFICATE_REQUEST_INVALID"
  | "DEVICE_KEY_UNAVAILABLE"
  | "DEVICE_ALREADY_ENROLLED"
  | "DEVICE_IDENTITY_NOT_FOUND"
  | "ENROLLMENT_GRANT_INVALID"
  | "ENROLLMENT_PROTOCOL_INCOMPATIBLE"
  | "IDENTITY_CONFIGURATION_INVALID"
  | "IDENTITY_KEY_CONFLICT"
  | "IDENTITY_REPOSITORY_CONFLICT"
  | "MAIN_IDENTITY_INVALID"
  | "MAIN_IDENTITY_PIN_MISMATCH"
  | "PEER_CERTIFICATE_EXPIRED"
  | "PEER_CERTIFICATE_INVALID"
  | "PEER_CERTIFICATE_NOT_YET_VALID"
  | "PEER_CERTIFICATE_REVOKED"
  | "PEER_CERTIFICATE_STALE"
  | "PEER_CERTIFICATE_UNKNOWN"
  | "PEER_IDENTITY_MISMATCH"
  | "ROTATION_ALREADY_PENDING"
  | "ROTATION_INVALID";

export class DeviceIdentityError extends Error {
  public readonly code: DeviceIdentityErrorCode;

  public constructor(code: DeviceIdentityErrorCode, message: string) {
    super(message);
    this.name = "DeviceIdentityError";
    this.code = code;
  }
}
